### ISSUE TITLE
Resetting StatMessage Data loop

### ISSUE THREAD

**Issue by Feliphysics** [LordAshes/TaleSpire-StatMessagingPlugin#2]
Loading a certain board with minis transformed on the previous version of CMP and StatMessaging causes StatMessaging to go into a Resetting StatMessaga Data followed by a NullReferenceException loop.

[Player.log](https://github.com/LordAshes/TaleSpire-StatMessagingPlugin/files/6835890/Player.log)

**Comment by LordAshes** [comment]
This looks like a legit issue.

Do you have steps that always cause this issue? Or was it a one time thing?

If you can reproduce it please try downloading CMP 5.0.1 and turn on the
diagnostic mode (by editing the R2ModMan configuration). This may help
identify what the issue is.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Feliphysics** [comment]
On my side it's easy to reproduce, all I have to do is load the certain board that causes it (it's not the only one that had minis already transformed before the 5.0 patch, but it's the only one that causes the loop).
Steps in this log:
1. opened up the game with CMP 5.0.1 in diagnostic mod;
2. loaded up a campaign which contains the "loop board" but not has its default board;
3. swapped to "loop board" (loop started);
4. swapped back to default board (loop continues until I close the game).

[Player.log](https://github.com/LordAshes/TaleSpire-StatMessagingPlugin/files/6836610/Player.log)

If there is any problem with the log and you need another one just let me know.

**Comment by LordAshes** [comment]
Ok, the additional logs didn't really help but I will look into it.

I may need to join your board in order to reproduce it. Would that be
possible?

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Feliphysics** [comment]
Yes, that wouldn't be a problem, tomorrow evening should work for me.

**Comment by LordAshes** [comment]
It will probably be Tuesday before I can get to this. I have work on monday
followed by a previous engagement.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Feliphysics** [comment]
Guess we can revisit this on Tuesday then, and if you still can't just let me know when you are available and I'll try to be there

**Comment by Feliphysics** [comment]
StatMessaging 1.6.3 seem to have fixed the problem, the board is now working perfectly, so I'll close the issue. Great job as always
